### ISSUE TITLE
[BUG] Robustness of "nb of days"

### ISSUE THREAD

**Issue by juvarlet** [juvarlet/a_table#55]
Traceback (most recent call last):
  File "/home/jv/Documents/gitRepos/a_table/main.py", line 995, in on_nb_days_changed
    self.current_menu.update(self.recipe_db, number)
  File "/home/jv/Documents/gitRepos/a_table/menu.py", line 233, in update
    print([recipe.name for recipe in self.table])
  File "/home/jv/Documents/gitRepos/a_table/menu.py", line 233, in <listcomp>
    print([recipe.name for recipe in self.table])
AttributeError: 'list' object has no attribute 'name'

**Comment by juvarlet** [comment]
bad print call in case of recipe edition (recipe -> list of recipe)
fixed by ju_branch commit 221408f24451e0a4d7b18cfd8417ae22bb9b9894
